# The name of this app. Must be unique within a project.
name: frontend

# The type of the application to build.
type: nodejs:6.9
dependencies:
    nodejs:
        webpack: "*"
        yarn: "*"

# The configuration of app when it is exposed to the web.
web:
    locations:
        "/":
            root: "dist"
            allow: true
            passthru: false
            index: ['index.html']

# The size of the persistent disk of the application (in MB).
disk: 128

# The mounts that will be performed when the package is deployed.
mounts: {}

# The hooks that will be performed when the package is deployed.
hooks:
    build: |
        yarn install
        npm run build:prod
