"https://{default}/":
    type: upstream
    upstream: "frontend:http"
    cache:
        enabled: false

"https://api.{default}/":
    type: upstream
    upstream: "api:http"
    cache:
        enabled: false
